name: Feature Request
description: Create a new ticket for a new feature request
title: "[REQUEST]: "
labels: [ enhancement ]
projects: [ Andret2344/surround-it ]
body:
  - type: textarea
    id: brief-summary
    attributes:
      label: Brief summary
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: extended-description
    attributes:
      label: Extended description
      description: If the request requires more details, please provide them here
      placeholder: Explain everything in detail
    validations:
      required: true
  - type: textarea
    id: open-questions
    attributes:
      label: Open questions
      description: What questions still remain unresolved?
      placeholder: Identify any unresolved issues
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Obligatory checks
      description: By submitting this issue, you confirm all of the following aspects.
      options:
        - label: I confirm that there is no issue that already covers this feature request.
          required: true
